export const REACT_TYPES_DECLARATION = `
declare namespace React {
  export type ReactNode = any;
  export type ReactElement<P = any, T = any> = any;
  export type ComponentType<P = any> = any;
  export type FC<P = any> = (props: P) => any;
  export type Key = string | number;
  export type Ref<T = any> = any;
  export type CSSProperties = Record<string, any>;
  export type MouseEvent<T = any> = any;
  export type ChangeEvent<T = any> = any;
  export type FormEvent<T = any> = any;
  export type KeyboardEvent<T = any> = any;
  export type ReactEventHandler<T = any> = (event: any) => void;

  export function useState<T>(initialState: T | (() => T)): [T, (newState: T | ((prev: T) => T)) => void];
  export function useEffect(effect: () => void | (() => void), deps?: readonly any[]): void;
  export function useMemo<T>(factory: () => T, deps: readonly any[] | undefined): T;
  export function useCallback<T extends (...args: any[]) => any>(callback: T, deps: readonly any[]): T;
  export function useRef<T>(initialValue?: T): { current: T };
  export function useContext<T>(context: any): T;
  export function useReducer<R extends (...args: any[]) => any>(reducer: R, initialArg: any, init?: any): any;
  export function createElement(type: any, props?: any, ...children: any[]): any;
  export const Fragment: any;
}

declare module 'react' {
  export = React;
  export as namespace React;
}

declare module 'react/jsx-runtime' {
  export const jsx: any;
  export const jsxs: any;
  export const Fragment: any;
}

declare global {
  namespace JSX {
    interface IntrinsicElements {
      [elemName: string]: any;
    }
    interface Element {
      [key: string]: any;
    }
  }
}
`;

export const LUCIDE_TYPES_DECLARATION = `
declare module 'lucide-react' {
  import * as React from 'react';

  export interface LucideProps {
    size?: string | number;
    color?: string;
    strokeWidth?: string | number;
    className?: string;
    style?: any;
    onClick?: (e?: any) => void;
    [key: string]: any;
  }

  export type LucideIcon = React.FC<LucideProps>;

  // Lucide React Icons
  export const Activity: LucideIcon;
  export const AlertCircle: LucideIcon;
  export const AlertOctagon: LucideIcon;
  export const AlertTriangle: LucideIcon;
  export const ArrowDown: LucideIcon;
  export const ArrowDownLeft: LucideIcon;
  export const ArrowDownRight: LucideIcon;
  export const ArrowLeft: LucideIcon;
  export const ArrowRight: LucideIcon;
  export const ArrowUp: LucideIcon;
  export const ArrowUpDown: LucideIcon;
  export const ArrowUpLeft: LucideIcon;
  export const ArrowUpRight: LucideIcon;
  export const BarChart: LucideIcon;
  export const BarChart2: LucideIcon;
  export const BarChart3: LucideIcon;
  export const Bell: LucideIcon;
  export const BellOff: LucideIcon;
  export const Bold: LucideIcon;
  export const Book: LucideIcon;
  export const BookOpen: LucideIcon;
  export const Bookmark: LucideIcon;
  export const Box: LucideIcon;
  export const Boxes: LucideIcon;
  export const Briefcase: LucideIcon;
  export const Calendar: LucideIcon;
  export const Camera: LucideIcon;
  export const Check: LucideIcon;
  export const CheckCircle: LucideIcon;
  export const CheckCircle2: LucideIcon;
  export const CheckSquare: LucideIcon;
  export const ChevronDown: LucideIcon;
  export const ChevronLeft: LucideIcon;
  export const ChevronRight: LucideIcon;
  export const ChevronUp: LucideIcon;
  export const ChevronsDown: LucideIcon;
  export const ChevronsLeft: LucideIcon;
  export const ChevronsRight: LucideIcon;
  export const ChevronsUp: LucideIcon;
  export const Circle: LucideIcon;
  export const Clock: LucideIcon;
  export const Cloud: LucideIcon;
  export const CloudDownload: LucideIcon;
  export const CloudOff: LucideIcon;
  export const CloudRain: LucideIcon;
  export const CloudSnow: LucideIcon;
  export const CloudUpload: LucideIcon;
  export const Code: LucideIcon;
  export const Code2: LucideIcon;
  export const Columns: LucideIcon;
  export const Command: LucideIcon;
  export const Compass: LucideIcon;
  export const Copy: LucideIcon;
  export const CornerDownLeft: LucideIcon;
  export const CornerDownRight: LucideIcon;
  export const CornerLeftDown: LucideIcon;
  export const CornerLeftUp: LucideIcon;
  export const CornerRightDown: LucideIcon;
  export const CornerRightUp: LucideIcon;
  export const CornerUpLeft: LucideIcon;
  export const CornerUpRight: LucideIcon;
  export const Cpu: LucideIcon;
  export const CreditCard: LucideIcon;
  export const Crop: LucideIcon;
  export const Crosshair: LucideIcon;
  export const Database: LucideIcon;
  export const Delete: LucideIcon;
  export const Disc: LucideIcon;
  export const DollarSign: LucideIcon;
  export const Download: LucideIcon;
  export const DownloadCloud: LucideIcon;
  export const Edit: LucideIcon;
  export const Edit2: LucideIcon;
  export const Edit3: LucideIcon;
  export const ExternalLink: LucideIcon;
  export const Eye: LucideIcon;
  export const EyeOff: LucideIcon;
  export const File: LucideIcon;
  export const FileCheck: LucideIcon;
  export const FileCode: LucideIcon;
  export const FileDigit: LucideIcon;
  export const FilePlus: LucideIcon;
  export const FileQuestion: LucideIcon;
  export const FileSpreadsheet: LucideIcon;
  export const FileText: LucideIcon;
  export const Files: LucideIcon;
  export const Film: LucideIcon;
  export const Filter: LucideIcon;
  export const Flag: LucideIcon;
  export const Folder: LucideIcon;
  export const FolderMinus: LucideIcon;
  export const FolderOpen: LucideIcon;
  export const FolderPlus: LucideIcon;
  export const GitBranch: LucideIcon;
  export const GitCommit: LucideIcon;
  export const GitMerge: LucideIcon;
  export const GitPullRequest: LucideIcon;
  export const Github: LucideIcon;
  export const Globe: LucideIcon;
  export const Grid: LucideIcon;
  export const HardDrive: LucideIcon;
  export const Hash: LucideIcon;
  export const Headphones: LucideIcon;
  export const Heart: LucideIcon;
  export const HelpCircle: LucideIcon;
  export const History: LucideIcon;
  export const Home: LucideIcon;
  export const Image: LucideIcon;
  export const Inbox: LucideIcon;
  export const Info: LucideIcon;
  export const Italic: LucideIcon;
  export const Key: LucideIcon;
  export const Keyboard: LucideIcon;
  export const Layers: LucideIcon;
  export const Layout: LucideIcon;
  export const LayoutDashboard: LucideIcon;
  export const LayoutGrid: LucideIcon;
  export const LifeBuoy: LucideIcon;
  export const Lightbulb: LucideIcon;
  export const LineChart: LucideIcon;
  export const Link: LucideIcon;
  export const Link2: LucideIcon;
  export const List: LucideIcon;
  export const ListOrdered: LucideIcon;
  export const Lock: LucideIcon;
  export const LogIn: LucideIcon;
  export const LogOut: LucideIcon;
  export const Mail: LucideIcon;
  export const Map: LucideIcon;
  export const MapPin: LucideIcon;
  export const Maximize: LucideIcon;
  export const Maximize2: LucideIcon;
  export const Menu: LucideIcon;
  export const MessageCircle: LucideIcon;
  export const MessageSquare: LucideIcon;
  export const Mic: LucideIcon;
  export const MicOff: LucideIcon;
  export const Minimize: LucideIcon;
  export const Minimize2: LucideIcon;
  export const Minus: LucideIcon;
  export const MinusCircle: LucideIcon;
  export const MinusSquare: LucideIcon;
  export const Monitor: LucideIcon;
  export const Moon: LucideIcon;
  export const MoreHorizontal: LucideIcon;
  export const MoreVertical: LucideIcon;
  export const Move: LucideIcon;
  export const Music: LucideIcon;
  export const Navigation: LucideIcon;
  export const Package: LucideIcon;
  export const PanelLeft: LucideIcon;
  export const PanelLeftClose: LucideIcon;
  export const PanelLeftOpen: LucideIcon;
  export const PanelRight: LucideIcon;
  export const PanelRightClose: LucideIcon;
  export const PanelRightOpen: LucideIcon;
  export const Paperclip: LucideIcon;
  export const Pause: LucideIcon;
  export const PauseCircle: LucideIcon;
  export const Percent: LucideIcon;
  export const Phone: LucideIcon;
  export const PhoneCall: LucideIcon;
  export const PhoneForwarded: LucideIcon;
  export const PhoneIncoming: LucideIcon;
  export const PhoneMissed: LucideIcon;
  export const PhoneOff: LucideIcon;
  export const PhoneOutgoing: LucideIcon;
  export const PieChart: LucideIcon;
  export const Play: LucideIcon;
  export const PlayCircle: LucideIcon;
  export const Plus: LucideIcon;
  export const PlusCircle: LucideIcon;
  export const PlusSquare: LucideIcon;
  export const Pocket: LucideIcon;
  export const Power: LucideIcon;
  export const Printer: LucideIcon;
  export const Puzzle: LucideIcon;
  export const Radio: LucideIcon;
  export const Redo: LucideIcon;
  export const RefreshCcw: LucideIcon;
  export const RefreshCw: LucideIcon;
  export const Repeat: LucideIcon;
  export const Rewind: LucideIcon;
  export const RotateCcw: LucideIcon;
  export const RotateCw: LucideIcon;
  export const Rows: LucideIcon;
  export const Rss: LucideIcon;
  export const Save: LucideIcon;
  export const Scissors: LucideIcon;
  export const Search: LucideIcon;
  export const Send: LucideIcon;
  export const Server: LucideIcon;
  export const Settings: LucideIcon;
  export const Share: LucideIcon;
  export const Share2: LucideIcon;
  export const Shield: LucideIcon;
  export const ShieldAlert: LucideIcon;
  export const ShieldCheck: LucideIcon;
  export const ShieldClose: LucideIcon;
  export const ShieldOff: LucideIcon;
  export const ShoppingBag: LucideIcon;
  export const ShoppingCart: LucideIcon;
  export const Shuffle: LucideIcon;
  export const Sidebar: LucideIcon;
  export const SkipBack: LucideIcon;
  export const SkipForward: LucideIcon;
  export const Slack: LucideIcon;
  export const Slash: LucideIcon;
  export const Sliders: LucideIcon;
  export const Smartphone: LucideIcon;
  export const Sparkles: LucideIcon;
  export const Speaker: LucideIcon;
  export const Square: LucideIcon;
  export const Star: LucideIcon;
  export const StopCircle: LucideIcon;
  export const Sun: LucideIcon;
  export const Sunrise: LucideIcon;
  export const Sunset: LucideIcon;
  export const Table: LucideIcon;
  export const Tablet: LucideIcon;
  export const Tag: LucideIcon;
  export const Target: LucideIcon;
  export const Terminal: LucideIcon;
  export const TerminalSquare: LucideIcon;
  export const Thermometer: LucideIcon;
  export const ThumbsDown: LucideIcon;
  export const ThumbsUp: LucideIcon;
  export const ToggleLeft: LucideIcon;
  export const ToggleRight: LucideIcon;
  export const Trash: LucideIcon;
  export const Trash2: LucideIcon;
  export const Trello: LucideIcon;
  export const TrendingDown: LucideIcon;
  export const TrendingUp: LucideIcon;
  export const Triangle: LucideIcon;
  export const Tv: LucideIcon;
  export const Twitch: LucideIcon;
  export const Twitter: LucideIcon;
  export const Type: LucideIcon;
  export const Umbrella: LucideIcon;
  export const Underline: LucideIcon;
  export const Undo: LucideIcon;
  export const Unlock: LucideIcon;
  export const Upload: LucideIcon;
  export const UploadCloud: LucideIcon;
  export const User: LucideIcon;
  export const UserCheck: LucideIcon;
  export const UserMinus: LucideIcon;
  export const UserPlus: LucideIcon;
  export const UserX: LucideIcon;
  export const Users: LucideIcon;
  export const Video: LucideIcon;
  export const VideoOff: LucideIcon;
  export const View: LucideIcon;
  export const Voicemail: LucideIcon;
  export const Volume: LucideIcon;
  export const Volume1: LucideIcon;
  export const Volume2: LucideIcon;
  export const VolumeX: LucideIcon;
  export const Watch: LucideIcon;
  export const Wifi: LucideIcon;
  export const WifiOff: LucideIcon;
  export const Wind: LucideIcon;
  export const Workflow: LucideIcon;
  export const Wrench: LucideIcon;
  export const X: LucideIcon;
  export const XCircle: LucideIcon;
  export const XOctagon: LucideIcon;
  export const XSquare: LucideIcon;
  export const Youtube: LucideIcon;
  export const Zap: LucideIcon;
  export const ZapOff: LucideIcon;
  export const ZoomIn: LucideIcon;
  export const ZoomOut: LucideIcon;

  const icons: { [key: string]: LucideIcon } & Record<string, any>;
  export default icons;
}
`;
